<<<<<<< HEAD
# Generated by Django 3.2.3 on 2021-05-30 14:45

from django.db import migrations, models
import django.db.models.deletion
=======
# Generated by Django 3.2 on 2021-05-30 11:15

from django.db import migrations, models
>>>>>>> 83f27afee888c4afde06d3493f85a085b76a5d2e


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='classSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleClass', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=50)),
                ('codeClasse', models.IntegerField()),
                ('creationDateClasse', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleTp', models.CharField(max_length=50)),
                ('creationDateTp', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PFES6.classsubject')),
            ],
        ),
        migrations.CreateModel(
            name='TD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleTd', models.CharField(max_length=50)),
                ('creationDateTd', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PFES6.classsubject')),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(max_length=50)),
                ('creationDateCourse', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PFES6.classsubject')),
            ],
        ),
        migrations.CreateModel(
            name='correction_TD_TP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('creationDateTdTp', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PFES6.classsubject')),
=======
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('picture', models.URLField(blank=True)),
                ('role', models.CharField(choices=[('s', 'student'), ('t', 'teacher')], max_length=2)),
>>>>>>> 83f27afee888c4afde06d3493f85a085b76a5d2e
            ],
        ),
    ]
