# Generated by Django 3.2.3 on 2021-05-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PFES6', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='correction_td_tp',
            name='corrFile',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='course',
            name='courseFile',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='td',
            name='tdFile',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='tp',
            name='tpFile',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
