# Generated by Django 3.2 on 2021-06-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PFES6', '0002_auto_20210601_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joinclass',
            old_name='usersId',
            new_name='userId',
        ),
        migrations.AlterField(
            model_name='classsubject',
            name='codeClasse',
            field=models.CharField(max_length=10),
        ),
    ]
