# Generated by Django 3.2.3 on 2021-05-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PFES6', '0002_auto_20210530_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='userApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FN', models.CharField(max_length=50)),
                ('LN', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('psw', models.CharField(max_length=50)),
                ('pic', models.ImageField(upload_to='pics')),
                ('role', models.CharField(max_length=20)),
            ],
        ),
    ]
