# Generated by Django 3.2.3 on 2021-05-30 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PFES6', '0003_userapp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userapp',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='userapp',
            old_name='FN',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='userapp',
            old_name='LN',
            new_name='Last_Name',
        ),
        migrations.RenameField(
            model_name='userapp',
            old_name='psw',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='userapp',
            old_name='pic',
            new_name='Picture',
        ),
        migrations.RenameField(
            model_name='userapp',
            old_name='role',
            new_name='Role',
        ),
    ]
