# Generated by Django 3.2.3 on 2021-05-30 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PFES6', '0004_auto_20210530_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userapp',
            name='Role',
        ),
    ]
