# Generated by Django 3.2.3 on 2021-05-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PFES6', '0005_remove_userapp_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapp',
            name='Role',
            field=models.CharField(choices=[('s', 'Student'), ('t', 'Teacher')], default='Teacher', max_length=2),
            preserve_default=False,
        ),
    ]
