# Generated by Django 3.2.3 on 2021-05-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PFES6', '0006_userapp_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapp',
            name='Role',
            field=models.CharField(choices=[('s', 'Student'), ('t', 'Teacher')], default='--', max_length=2),
        ),
    ]
