# Generated by Django 3.2.3 on 2021-05-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PFES6', '0008_alter_userapp_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapp',
            name='Role',
            field=models.CharField(choices=[('s', 'Student'), ('t', 'Teacher'), ('-', '---')], default='none', max_length=3, null=True),
        ),
    ]
